[package]
name = 'networktool'
version = '0.0.0'
edition = '2021'

[build-dependencies]
tauri-build = { version = "*", features = [] }

[dependencies]
tauri = { version = "*", features = [] }
local-ip-address = "*"

[features]
custom-protocol = ['tauri/custom-protocol']
